name: release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: pnpm/setup@84cb39b217b10273981911c288cd62326dc7c6d2 # v2
        with:
          cache: true

      - name: Prepare build environment
        run: pnpm dev:prepare

      - run: pnpm build

      - name: publish nightly release
        run: pnpm pkg-pr-new publish --compact --pnpm
