name: release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: pnpm/setup@fbda4c85fc2e1e08721cd8763afea8f48d60f024 # v3.0.0
        with:
          cache: true

      - name: Prepare build environment
        run: pnpm dev:prepare

      - run: pnpm build

      - name: publish nightly release
        run: pnpm pkg-pr-new publish --compact --pnpm
